package tor

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ExitCountry represents an ISO 3166-1 alpha-2 country code used for exit nodes.
type ExitCountry struct {
	Code string
	Name string
}

// KnownCountries is a curated list of countries commonly available as Tor exit nodes.
var KnownCountries = []ExitCountry{
	{Code: "US", Name: "United States"},
	{Code: "DE", Name: "Germany"},
	{Code: "NL", Name: "Netherlands"},
	{Code: "FR", Name: "France"},
	{Code: "SE", Name: "Sweden"},
	{Code: "CH", Name: "Switzerland"},
	{Code: "NO", Name: "Norway"},
	{Code: "IS", Name: "Iceland"},
	{Code: "GB", Name: "United Kingdom"},
	{Code: "CA", Name: "Canada"},
	{Code: "JP", Name: "Japan"},
	{Code: "SG", Name: "Singapore"},
	{Code: "AU", Name: "Australia"},
	{Code: "NZ", Name: "New Zealand"},
	{Code: "AT", Name: "Austria"},
	{Code: "BE", Name: "Belgium"},
	{Code: "FI", Name: "Finland"},
	{Code: "CZ", Name: "Czech Republic"},
	{Code: "RO", Name: "Romania"},
	{Code: "LU", Name: "Luxembourg"},
}

// TorConfig holds all parameters for generating a torrc file.
type TorConfig struct {
	SocksPort      int
	ControlPort    int
	DataDir        string
	LogFile        string
	ExitNodes      []string // ISO codes; empty means any
	StrictExitNodes bool
	Bridges        []Bridge
	UseBridges     bool
	// HashedControlPassword is the hashed password for the control port.
	// Generate with: tor --hash-password "yourpassword"
	HashedControlPassword string
	// CookieAuthentication enables cookie-based auth (more secure than password).
	CookieAuthentication bool
	// DNSPort exposes a local DNS resolver over Tor.
	DNSPort int
	// TransPort enables transparent proxying (Linux only).
	TransPort int
	// SafeSocks rejects applications sending DNS names in SOCKS4 (privacy).
	SafeSocks bool
}

// DefaultConfig returns a safe, sensible default TorConfig.
func DefaultConfig() TorConfig {
	homeDir, _ := os.UserHomeDir()
	return TorConfig{
		SocksPort:            9050,
		ControlPort:          9051,
		DataDir:              filepath.Join(homeDir, ".local", "share", "tor-manager"),
		LogFile:              "",
		SafeSocks:            true,
		CookieAuthentication: true,
	}
}

// Validate checks the config for obvious errors before writing.
func (cfg TorConfig) Validate() error {
	if cfg.SocksPort < 1 || cfg.SocksPort > 65535 {
		return fmt.Errorf("tor: invalid SocksPort %d", cfg.SocksPort)
	}
	if cfg.ControlPort < 1 || cfg.ControlPort > 65535 {
		return fmt.Errorf("tor: invalid ControlPort %d", cfg.ControlPort)
	}
	if cfg.SocksPort == cfg.ControlPort {
		return fmt.Errorf("tor: SocksPort and ControlPort must differ")
	}
	if cfg.DataDir == "" {
		return fmt.Errorf("tor: DataDir must not be empty")
	}
	if cfg.HashedControlPassword == "" && !cfg.CookieAuthentication {
		return fmt.Errorf("tor: control port has no authentication configured — this is insecure")
	}
	for _, code := range cfg.ExitNodes {
		if len(code) != 2 {
			return fmt.Errorf("tor: invalid country code %q (must be 2 chars)", code)
		}
	}
	return nil
}

// GenerateTorrc produces the content of a torrc file from this config.
func (cfg TorConfig) GenerateTorrc() string {
	var b strings.Builder

	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}
	comment := func(text string) {
		fmt.Fprintf(&b, "# %s\n", text)
	}

	comment("Generated by tor-manager — do not edit by hand")
	comment("https://github.com/you/tor-manager")
	b.WriteString("\n")

	comment("--- Network ---")
	w("SocksPort %d", cfg.SocksPort)
	if cfg.DNSPort > 0 {
		w("DNSPort %d", cfg.DNSPort)
	}
	if cfg.TransPort > 0 {
		w("TransPort %d", cfg.TransPort)
	}
	b.WriteString("\n")

	comment("--- Control Port ---")
	w("ControlPort %d", cfg.ControlPort)
	if cfg.CookieAuthentication {
		w("CookieAuthentication 1")
		w("CookieAuthFile %s", filepath.Join(cfg.DataDir, "control_auth_cookie"))
	}
	if cfg.HashedControlPassword != "" {
		w("HashedControlPassword %s", cfg.HashedControlPassword)
	}
	b.WriteString("\n")

	comment("--- Storage ---")
	w("DataDirectory %s", cfg.DataDir)
	if cfg.LogFile != "" {
		w("Log notice file %s", cfg.LogFile)
	} else {
		w("Log notice stdout")
	}
	b.WriteString("\n")

	comment("--- Privacy & Security ---")
	if cfg.SafeSocks {
		w("SafeSocks 1")
	}
	// Reduce timing attacks with stream isolation
	w("IsolateClientAddr 1")
	w("IsolateClientProtocol 1")
	// Prevent DNS leaks from apps
	w("TestSocks 1")
	b.WriteString("\n")

	if len(cfg.ExitNodes) > 0 {
		comment("--- Exit Node Selection ---")
		// Format: {US},{DE},{NL}
		var codes []string
		for _, code := range cfg.ExitNodes {
			codes = append(codes, "{"+strings.ToUpper(code)+"}")
		}
		w("ExitNodes %s", strings.Join(codes, ","))
		if cfg.StrictExitNodes {
			w("StrictNodes 1")
		}
		b.WriteString("\n")
	}

	if cfg.UseBridges && len(cfg.Bridges) > 0 {
		comment("--- Bridges ---")
		w("UseBridges 1")
		for _, br := range cfg.Bridges {
			w("Bridge %s", br.String())
		}
		b.WriteString("\n")
	}

	return b.String()
}

// WriteToFile writes the torrc to the given path, creating directories as needed.
// The file is written with mode 0600 (owner-readable only).
func (cfg TorConfig) WriteToFile(path string) error {
	if err := cfg.Validate(); err != nil {
		return err
	}

	// Ensure parent directory exists
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("tor: create config dir: %w", err)
	}

	content := cfg.GenerateTorrc()
	// Write atomically using a temp file + rename
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0600); err != nil {
		return fmt.Errorf("tor: write torrc: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp) //nolint:errcheck
		return fmt.Errorf("tor: rename torrc: %w", err)
	}
	return nil
}

// EnsureDataDir creates the data directory with correct permissions.
func (cfg TorConfig) EnsureDataDir() error {
	return os.MkdirAll(cfg.DataDir, 0700)
}
